In [1]:
import tensorflow as tf
import keras
from keras.models import Sequential
import numpy as np

In [2]:
model=Sequential()
model_part1=tf.keras.applications.ResNet50(
    include_top=False,
    weights="imagenet",
    input_tensor=None,
    input_shape=(32,32,3),
    pooling=None,
    classes=10,
)

In [3]:
for layer in model_part1.layers:
    layer.trainable=False

In [4]:
model.add(model_part1)

In [5]:
from keras.layers import Flatten,Dense

In [6]:

model.add(Flatten())
model.add(Dense(512,activation='relu'))
model.add(Dense(10,activation='softmax'))

In [7]:
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 resnet50 (Functional)       (None, 1, 1, 2048)        23587712  
                                                                 
 flatten (Flatten)           (None, 2048)              0         
                                                                 
 dense (Dense)               (None, 512)               1049088   
                                                                 
 dense_1 (Dense)             (None, 10)                5130      
                                                                 
Total params: 24,641,930
Trainable params: 1,054,218
Non-trainable params: 23,587,712
_________________________________________________________________


In [8]:
fashion_mnist=keras.datasets.fashion_mnist

In [9]:
(X_train,Y_train),(X_test,Y_test)=fashion_mnist.load_data()

In [10]:
X_train.shape

(60000, 28, 28)

In [11]:
X_train = np.expand_dims(X_train, axis=-1)
X_train = tf.image.resize(X_train, [32,32]) 

In [12]:
X_train.shape

TensorShape([60000, 32, 32, 1])

In [13]:
X_test = np.expand_dims(X_test, axis=-1)
X_test = tf.image.resize(X_test, [32,32])

In [14]:
X_test.shape

TensorShape([10000, 32, 32, 1])

In [15]:
train_files=[]

In [16]:
import cv2

In [17]:
for i,fi in enumerate(X_train):
    
    im_array=np.array(fi)
    img= cv2.cvtColor(im_array,cv2.COLOR_GRAY2RGB)
    train_files.append(img)

In [18]:
test_files=[]

In [19]:
for i,fi in enumerate(X_test):
    im_array=np.array(fi)
    img= cv2.cvtColor(im_array,cv2.COLOR_GRAY2RGB)
    test_files.append(img)

In [20]:
import matplotlib.pyplot as plt

In [21]:
from PIL import Image

In [22]:
X_train

<tf.Tensor: shape=(60000, 32, 32, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
  

In [23]:
train_files

[array([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],
 
        ...,
 
        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]], dtype=float32),
 array([[[0., 0., 0.],
         [0., 0.,

In [24]:
train_files[0].shape

(32, 32, 3)

In [25]:
X1_train=np.zeros((len(train_files),32,32,3))
for i,fi in enumerate(train_files):
    fi_array=np.array(fi)
    if(fi_array.shape[0]==32 and fi_array.shape[1]==32):
        X1_train[i,:,:,:]=fi_array

In [26]:
X1_test=np.zeros((len(test_files),32,32,3))
for i,fi in enumerate(test_files):
    fi_array=np.array(fi)
    if(fi_array.shape[0]==32 and fi_array.shape[1]==32):
        X1_test[i,:,:,:]=fi_array

In [27]:
model.compile(optimizer=keras.optimizers.Adam(learning_rate= 1e-3),
loss='sparse_categorical_crossentropy',
metrics=['accuracy'])

In [28]:
model.fit(X1_train, Y_train, epochs=10, batch_size=15, validation_data=(X1_test, Y_test))

Epoch 1/10
4000/4000 [==============================] - 200s 49ms/step - loss: 0.5378 - accuracy: 0.8127 - val_loss: 0.4868 - val_accuracy: 0.8183
Epoch 2/10
4000/4000 [==============================] - 205s 51ms/step - loss: 0.4042 - accuracy: 0.8495 - val_loss: 0.4039 - val_accuracy: 0.8579
Epoch 3/10
4000/4000 [==============================] - 247s 62ms/step - loss: 0.3665 - accuracy: 0.8629 - val_loss: 0.4294 - val_accuracy: 0.8493
Epoch 4/10
4000/4000 [==============================] - 239s 60ms/step - loss: 0.3414 - accuracy: 0.8736 - val_loss: 0.4318 - val_accuracy: 0.8540
Epoch 5/10
4000/4000 [==============================] - 234s 58ms/step - loss: 0.3186 - accuracy: 0.8813 - val_loss: 0.4146 - val_accuracy: 0.8632
Epoch 6/10
4000/4000 [==============================] - 199s 50ms/step - loss: 0.2995 - accuracy: 0.8874 - val_loss: 0.4517 - val_accuracy: 0.8488
Epoch 7/10
4000/4000 [==============================] - 192s 48ms/step - loss: 0.2857 - accuracy: 0.8932 - val_loss: 0

In [31]:
X1_test


array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 

In [32]:
p=model.predict(X1_test[:3])

1/1 [==============================] - 8s 8s/step


In [33]:
p.shape

(3, 10)

In [35]:
Y_predicted=model.predict(X1_test)

313/313 [==============================] - 27s 84ms/step


In [36]:
Y_predicted

array([[1.4389980e-26, 4.1282939e-33, 0.0000000e+00, ..., 2.7215920e-11,
        2.1585801e-16, 1.0000000e+00],
       [3.7848196e-07, 6.9309212e-13, 9.9953711e-01, ..., 4.5776901e-27,
        9.4540695e-11, 7.9401030e-27],
       [1.7798196e-10, 1.0000000e+00, 2.3298521e-10, ..., 9.9519057e-22,
        3.8272841e-15, 1.2359210e-27],
       ...,
       [3.9535522e-23, 7.6319808e-25, 2.2262332e-17, ..., 2.7342726e-18,
        1.0000000e+00, 2.4000670e-21],
       [1.5220644e-21, 1.0000000e+00, 2.1091875e-24, ..., 0.0000000e+00,
        1.7334376e-29, 0.0000000e+00],
       [7.2181458e-05, 1.3114418e-05, 9.8260629e-05, ..., 4.9602404e-01,
        2.4894545e-02, 2.3817016e-01]], dtype=float32)

In [37]:
results = model.evaluate(X1_test, Y_test, batch_size=128)

79/79 [==============================] - 17s 207ms/step - loss: 0.4729 - accuracy: 0.8609


In [38]:
results

[0.4729461371898651, 0.8608999848365784]